HTTP
### Teste die Intent IF Abfrage
POST http://localhost:8080/documentation/123/room/456/entry/create
Content-Type: application/json

{
  "elementId": "test-elem",
  "description": "Test",
  "intent": "CONTROL_ACTION"
}