version: '3'
services:
  db:
    image: mongo:latest
    container_name: "db"
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
  checklist-app:
    container_name: "checklist-app"
    build: ./boundary
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://db:27017/checklist_db
      SPRING_DATA_MONGODB_HOST: db
      SPRING_PROFILES_ACTIVE: "docker"


volumes:
  mongodb-data: